In [8]:
import pandas as pd
eval_result_file_path = "tb_files/Bert/MC-V2-ALL/base/310K/eval_result_details.csv"

In [16]:
#df_eval = pd.read_csv(eval_result_file_path, names=['pred','actual'],sep=',', header=0)
df_eval = pd.read_csv(eval_result_file_path,sep=',', header=0, index_col=0)

In [17]:
print(len(df_eval))

10000

In [18]:
df_eval.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,pred,actual
0,0.005715,0.001242,0.001110,0.250022,0.236946,0.005630,0.021430,0.019752,0.076420,0.008402,0.024767,0.263023,0.005418,0.002121,0.053636,0.024368,11.0,3.0
1,0.001654,0.001623,0.000280,0.002169,0.012603,0.000474,0.000600,0.001971,0.003881,0.151460,0.000431,0.003549,0.001052,0.000229,0.809901,0.008122,14.0,14.0
2,0.003568,0.002175,0.000506,0.001640,0.038023,0.000287,0.001180,0.014170,0.001862,0.903851,0.000519,0.000824,0.014990,0.000761,0.014208,0.001435,9.0,9.0
3,0.000753,0.002113,0.000355,0.001832,0.022788,0.000616,0.001701,0.001264,0.552715,0.014670,0.001338,0.183023,0.002983,0.000350,0.119469,0.094029,8.0,8.0
4,0.006010,0.913993,0.000319,0.000842,0.002878,0.000227,0.001221,0.001472,0.037547,0.000175,0.000706,0.001475,0.000822,0.000305,0.008264,0.023743,1.0,1.0

In [20]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(df_eval['actual'], df_eval['pred'], target_names=['경제민주화', 
'교통/건축/국토', 
'농산어촌',
'문화/예술/체육/언론',
'미래',
'반려동물',
'보건복지',
'성장동력',
'안전/환경',
'외교/통일/국방',
'육아/교육',
'인권/성평등',
'일자리',
'저출산/고령화대책',
'정치개혁',
'행정']))

              precision    recall  f1-score   support

       경제민주화       0.59      0.53      0.56       569
    교통/건축/국토       0.63      0.87      0.73       907
        농산어촌       0.54      0.57      0.56        47
 문화/예술/체육/언론       0.64      0.76      0.70       534
          미래       0.36      0.15      0.21       540
        반려동물       0.83      0.92      0.87       113
        보건복지       0.67      0.66      0.66       699
        성장동력       0.43      0.12      0.18       232
       안전/환경       0.65      0.61      0.63       864
    외교/통일/국방       0.66      0.74      0.70       843
       육아/교육       0.67      0.84      0.75       643
      인권/성평등       0.64      0.57      0.60       952
         일자리       0.60      0.73      0.66       708
   저출산/고령화대책       0.61      0.36      0.45       100
        정치개혁       0.66      0.67      0.67      1658
          행정       0.42      0.30      0.35       591

    accuracy                           0.63     10000
   macro avg       0.60      0.59      0.58     10000
weighted avg       0.61      0.63      0.61     10000